server:
  port: 9010
spring:
  application:
    name: pay
  rabbitmq:
    host: 192.168.0.101
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
wxpay:
  notity_url: http://kaiwx.cross.echosite.cn/wxpay/notity